In [1]:
from dataloader import train_loader,test_loader

print("Train data:", len(train_loader))
print("Test data:", len(test_loader))
print("shape of image and mask:", next(iter(train_loader))[0].shape, next(iter(train_loader))[1].shape)

Train data: 90
Test data: 6
shape of image and mask: torch.Size([4, 3, 96, 128]) torch.Size([4, 1, 96, 128])
Train data: 90
Test data: 6
shape of image and mask: torch.Size([4, 3, 96, 128]) torch.Size([4, 1, 96, 128])


In [2]:
import sys
sys.path.append(r'C:\Users\Debajyoti\OneDrive\Desktop\Brain tumor disease\src')
from training import train

from models.U_net import U_Net_Model

model = U_Net_Model(in_channels=3, out_channels=1, dropouts=0.1)
save_path = r"C:\Users\Debajyoti\OneDrive\Desktop\Brain tumor disease\src\models\segmentation_weight.h5"
train(model,train_loader,10,save_path)


Epoch 1/10: Loss = -0.0384, Accuracy = 0.9825
Epoch 2/10: Loss = -0.0792, Accuracy = 0.9825
Epoch 3/10: Loss = -0.0801, Accuracy = 0.9825
Epoch 4/10: Loss = -0.0801, Accuracy = 0.9825
Epoch 5/10: Loss = -0.0801, Accuracy = 0.9825
Epoch 6/10: Loss = -0.0809, Accuracy = 0.9825
Epoch 7/10: Loss = -0.0815, Accuracy = 0.9825
Epoch 8/10: Loss = -0.0843, Accuracy = 0.9825
Epoch 9/10: Loss = -0.0821, Accuracy = 0.9825
Epoch 10/10: Loss = -0.0787, Accuracy = 0.9825
Model saved to C:\Users\Debajyoti\OneDrive\Desktop\Brain tumor disease\src\models\segmentation_weight.h5


{'loss': [-0.038365153554413056,
  -0.07921834014770057,
  -0.080068368707887,
  -0.08006836844918629,
  -0.08006836667449937,
  -0.08085089051164687,
  -0.0814751771175199,
  -0.08427722946637206,
  -0.08212753121948077,
  -0.0787390352330274],
 'accuracy': [0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047,
  0.9824948208450047]}

In [5]:
import numpy as np
from PIL import Image

mask_file_path = r"C:\Users\Debajyoti\OneDrive\Desktop\Brain tumor disease\Dataset\Train folder\masks\gg-1-_jpg.rf.14ec1b789c991a8fa4a13cfe7754e655.jpg"
mask = Image.open(mask_file_path)

# Convert the PIL Image to a NumPy array
mask_array = np.array(mask)
print(mask_array)
no_of_ones = (mask_array == 1).sum()
print(no_of_ones)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
464
